import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sneyder Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen flex items-center bg-slate-900 justify-center max-sm:text-xs pb-16 pt-16 relative"}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
